[package]
name = "ai"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.19.1", features = ["std", "tui", "autodiff", "wgpu"] }
crossterm = "0.29.0"
rand = "0.9.2"
ratatui = "0.29.0"
replace_with = "0.1.8"
tetris-core = { path = "../tetris-core" }
